/// Flutter icons VtrackerIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VtrackerIcons
///      fonts:
///       - asset: fonts/VtrackerIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VtrackerIcons {
  VtrackerIcons._();

  static const _kFontFam = 'VtrackerIcons';
  static const String? _kFontPkg = null;

  static const IconData static =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tier =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
